name: Merge Fork

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:      # manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      - name: Add upstream
        run: git remote add upstream https://github.com/Equicord/Equicord.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream into fork
        run: | 
          git config --global user.name "GitHub-Actions"
          git config --global user.email actions@github.com
          
          git merge upstream/main --allow-unrelated-histories -m "Sync from upstream"

      - name: Push changes
        run: git push origin main
